// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabGB17bMklCqYF1g1U1cTq2NjDN3dYC8',
    appId: '1:221023005778:web:36b9f56ad50e4d9535438b',
    messagingSenderId: '221023005778',
    projectId: 'sth-app',
    authDomain: 'sth-app.firebaseapp.com',
    databaseURL: 'https://sth-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sth-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDjgf_Ts_qXNBN6w-7bJZPGYbAF9X7wG8',
    appId: '1:221023005778:android:061e6826dd77976735438b',
    messagingSenderId: '221023005778',
    projectId: 'sth-app',
    databaseURL: 'https://sth-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sth-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0qTJUyTGD9RArDBd8GoPMjRs7edSYvZc',
    appId: '1:221023005778:ios:db35fefd0aea169d35438b',
    messagingSenderId: '221023005778',
    projectId: 'sth-app',
    databaseURL: 'https://sth-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sth-app.appspot.com',
    iosClientId: '221023005778-j1kcsrst9v9unh7qda0t1n5kc2uotuna.apps.googleusercontent.com',
    iosBundleId: 'com.example.sthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0qTJUyTGD9RArDBd8GoPMjRs7edSYvZc',
    appId: '1:221023005778:ios:db35fefd0aea169d35438b',
    messagingSenderId: '221023005778',
    projectId: 'sth-app',
    databaseURL: 'https://sth-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sth-app.appspot.com',
    iosClientId: '221023005778-j1kcsrst9v9unh7qda0t1n5kc2uotuna.apps.googleusercontent.com',
    iosBundleId: 'com.example.sthApp',
  );
}
